### ISSUE TITLE
adViewDidEnd delegate method is not called for Instream video ads on iOS device

### ISSUE THREAD

**Issue by globaltakeoff** [fbsamples/audience-network#103]
Hi Team,

The following issue is there for a long time on iOS device.
In Instream video ad "**adViewDidEnd**" delegate method is not getting called. Below is the scenario.
After downloading the sample app, install pods, run app, 
tap on **Instream** in **Ad Samples**
tap on "Load Ad"
(after "Ad loaded")
tap on "Show!"
while the video is playing
tap on the video once to pause and tap on the video again to play
wait for the ad to finish
the "adViewDidEnd" delegate method will not get called in this case.

This is happening for every odd clicks, assuming **pause** and then **play** event as one click.

**Comment by daniel-huri** [comment]
Please upgrade to the latest SDK version and report back if the problem persists.
