### ISSUE TITLE
Android SDK - ad event and data

### ISSUE THREAD

**Issue by giladna** [fbsamples/audience-network#104]
hi,
https://github.com/fbsamples/audience-network/blob/master/samples/android/AdUnitsSample/AdUnitsSample/src/main/java/com/facebook/samples/AdUnitsSample/fragments/InstreamVideoFragment.java

FB SDK is not exposing important data for app devs.
No API to receive the play/pause events which are done via the ui buttons
No Ability to get current ad position and duration
No ability to get if ad is skippable or not and what is the skip offset.

if this can be done I would love to get that tip
if not please add it.

Thanks!
-Gilad

**Comment by Faboor** [comment]
Instream ads have been deprecated and referenced code removed.
