### ISSUE TITLE
NativeAd not clickable in UITableView

### ISSUE THREAD

**Issue by neobie** [fbsamples/audience-network#105]
The NativeAd displaying correctly, and registerViewForInteraction is implemented.
But, the ad is just not clickable. Only Adchoice react to the tap.

Try everything I can but still no luck.

It is working for iOS SDK v4.28.1

After upgrading to v4.99.3 - v5.4.0, nothing works.

`[nativeAd registerViewForInteraction:cell mediaView:cell.adCoverMediaView iconView:cell.adIconView viewController:self clickableViews:@[cell.adIconView, cell.adBodyLabel, cell.adTitleLabel] ];`

`[nativeAd registerViewForInteraction:cell mediaView:cell.adCoverMediaView iconView:cell.adIconView viewController:self]`

**Comment by neobie** [comment]
It doesn't work in Android ListView too.
Seems like new SDK registerViewForInteraction method has some problem ?

**Comment by martarodriguezm** [comment]
Same problem here, any update?

**Comment by daniel-huri** [comment]
Please update to the latest SDK version and report back if the issue still is happening. Closing for now as it seems to be a stale thread.
