### ISSUE TITLE
[iOS] In-stream Ads

### ISSUE THREAD

**Issue by WCChimiiz** [fbsamples/audience-network#106]
When I click on in-stream ads, ads is pause then I click again ads is play but after ads did end ads  is stop but not call adViewDidEnd function, then if I click on ads again an ads will re-play, and if I do same before step I still have issue, but if I don't click anything on ads when ads is playing after ads did end this call adViewDidEnd function.

**Comment by Faboor** [comment]
Instream ads have been deprecated.
