### ISSUE TITLE
Reporting API async flow: how long do we need to wait after getting the query_ids 

### ISSUE THREAD

**Issue by louisguitton** [fbsamples/audience-network#108]
In the samples readme, you say 
> After you fetch query ids successfully, please wait for a few seconds (i.e. 10 seconds) before you send another "async" request with query ids such that you are guaranteed to get results. Also, please do not try to request more than 50 times within 60 seconds.

In the [docs](https://developers.facebook.com/docs/audience-network/reporting-api), there is nothing specified for this.

We implemented a custom API client for the Facebook Audience Network Reporting API, we're trying to fetch the reports for 1 day, `breakdowns=["country", "placement_name"]` (we have 26 placements and 225 countries), for 5 metrics.
We're already using filters to batch the countries 5 by 5.
We're already waiting 30 seconds between the successful async POST request and the async GET request.
We've tried retrying and waiting for the async GET request, in the same fashion than https://github.com/fbsamples/audience-network/blob/master/samples/python/ReportingAPISamples/adnw_examples.py#L83-L93

Yet, we're still at some point rate limited it seems because we get the following response
```json
{
   "data": [
      {
         "query_id": "2438fb3df7d59905e2897dc88592a3c1",
         "status": "requested"
      }
   ]
}
```

What are we doing wrong? what are the suggested approaches? Where can I find the documentation for the "status" logic in the response of the `GET /v5.0/{application-id}/adnetworkanalytics_results` [docs here](https://developers.facebook.com/docs/graph-api/reference/application/adnetworkanalytics_results/)

**Comment by sherifelkhatib** [comment]
Hey @louisguitton, please check the latest documentation and if the problem persists, please report it on the [publisher support portal](https://www.facebook.com/business/publishersupport).
