### ISSUE TITLE
Encounter error 2002 and OOM issues after upgrade Sdk

### ISSUE THREAD

**Issue by elirex** [fbsamples/audience-network#109]
We encounter errorCode 2002 and OOM issues when upgraded SDK to v5.6.0, but that issues do not exist v5.1.0, please check. Thanks.

**Comment by gwheet** [comment]
Small number of these errors is acceptable. Please upgrade to the latest SDK and use the [bug report tool](https://developers.facebook.com/support/bugs/) if you still experience these issues.
