### ISSUE TITLE
Your Documentation SUUUUUUUUUUUUUUUUKS!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by GratePic** [fbsamples/audience-network#113]
I did the following on an IOS swift 4 app

*Added pod 'FBAudienceNetwork' to the pod file

*Executed pod install

*Cleaned and Built the app

Following error:
  "_OBJC_CLASS_$_FBSDKBasicUtility", referenced from:
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Solutions: 

1) Removed the pod and added it back (app builds)

2) Rolled the SDK back to pod 'FBAudienceNetwork', '4.25.0' (app builds)

3) #import <FBAudienceNetwork/FBAudienceNetwork.h> (app builds)

Dear FACEBOOK, 

Stop being a bunch assholes and add swift examples for Facebook Audience Network integration. I know you are busy right now trying to ensure the US presidential election doesn't get hacked again, but that's no excuse. Also, your documentation needs to be much clearer, and you need to have a section for IOS swift. 

Sincerely,
Don't turn off my access...

**Comment by daniel-huri** [comment]
Hey @GratePic, 
Please check out the [Swift sample app](https://github.com/fbsamples/audience-network/tree/master/samples/ios/FANSample).
