### ISSUE TITLE
RecyclerView lag with native video ads

### ISSUE THREAD

**Issue by saadbzu** [fbsamples/audience-network#114]
I use native video ads in my recyclerview, it work fine but the scrolling of my recyclerview is very slow. Please suggest me any solution.

**Comment by sherifelkhatib** [comment]
Hey @saadbzu, please make sure you are using the latest version of the SDK and you are following the best practices to integrate the SDK.
In case the problem persists, please use the [publisher support portal](https://www.facebook.com/business/publishersupport).
