### ISSUE TITLE
How to analyse and optimize the accidental click problem of the native ads with Audience Network

### ISSUE THREAD

**Issue by icefoggy** [fbsamples/audience-network#115]
I have several apps that use audience network. After getting a amount of ads impressions, I often get the prompt of unqualified or near unqualified quality. The problem of unqualified quality is that the accidentally clicks. At first, I thought it was the user's quick swiping of the screen and other operations that might trigger the click of the advertisement. However, by repeatedly checking the realization of the advertisement position, I found that even the clickable widgets of the advertisement would be controlled in a very small area, such as the CTA button, and similar results would be received, so I have two questions about accidentally clicks:
1、What's the rules of the accidental click, can sliding gesture be regarded as an accidentally click?
2、How can I continue to optimize the quality problem when the clickable area is already controlled in a small area such as CTA button?

**Comment by sherifelkhatib** [comment]
Hey @icefoggy, 
For policy questions, please review the [Audience Network Support documentation](https://developers.facebook.com/docs/audience-network/support) and contact us via the support portal linked there.
