### ISSUE TITLE
About banner ads refreshing

### ISSUE THREAD

**Issue by tirumala007** [fbsamples/audience-network#121]
I have an app working fine. I am getting the banner ads. But there is only one ad is present throughout the activity(if an activity is opened for 5 minutes, then there is only one ad. and it does not get refreshed.). I want it to show different ads after sometime. Should i call the load method manually ?  please help me

**Comment by daniel-huri** [comment]
You can regenerate the ad unit view and call load on the ad.
Please refer to the sample apps provided in the repository for extended examples
