### ISSUE TITLE
Too much size added in assets increasing APK size

### ISSUE THREAD

**Issue by Hanzala717** [fbsamples/audience-network#122]
after updating to latest version of SDK it adds 1.6MB file size in assets which increasing APK size that's incredibly very high like our app size is 2 MB and after adding this SDK it reaches almost 4 MB.

how to reduce that side ?

**Comment by gwheet** [comment]
The SDK includes variety of ad formats for the best monetisation that naturally increases the size. We don't have immediate plans to address this problem.
If size is absolutely critical for you, you can try to extract ads SDK into separate dynamically downloadable module: https://developer.android.com/guide/app-bundle/play-feature-delivery
