### ISSUE TITLE
Always got this error com.facebook.ads.AdError@26b7ba5

### ISSUE THREAD

**Issue by dipankar108** [fbsamples/audience-network#123]
interstitial = new com.facebook.ads.InterstitialAd(this, "MyplacementId");
                InterstitialAdListener interstitialAdListener = new InterstitialAdListener() {

                    @Override
                    public void onError(Ad ad, AdError adError) {
                        Log.v(TAG, " interstitial ads not loaded"+adError.toString());
                 
                    }

                    @Override
                    public void onAdLoaded(Ad ad) {
                
                    }

                    @Override
                    public void onAdClicked(Ad ad) {
                        Log.v(TAG, " interstitial ads  onclicked");
                    }

                    @Override
                    public void onLoggingImpression(Ad ad) {
                        Log.v(TAG, " interstitial ads  login");
                    }

                    @Override
                    public void onInterstitialDisplayed(Ad ad) {
                        Log.v(TAG, " interstitial ads  displayed");
                    }

                    @Override
                    public void onInterstitialDismissed(Ad ad) {
                        Log.v(TAG, " interstitial ads  dismissed");
                    }
                };
                interstitial.loadAd(
                        interstitial.buildLoadAdConfig()
                                .withAdListener(interstitialAdListener)
                                .build());

**Comment by Faboor** [comment]
Please provide the error code and error message from the `AdError`. Most likely you have misconfigured your placement. See https://developers.facebook.com/docs/audience-network/guides/test/checklist-errors/ for most common errors.

Closing as report not actionable.
