### ISSUE TITLE
Warnings in iOS SDK

### ISSUE THREAD

**Issue by BeaverAA** [fbsamples/audience-network#125]
Hello, i see these warnings in FBAudienceNetwork (sdk version = 0.6.0)

![image](https://user-images.githubusercontent.com/30597930/95346855-f01d5b00-08c4-11eb-9847-d4422c7a0bda.png)

I have warnings enabled as errors, so this actually causes the build to fail.

Are you going to fix these warnings in future releases?

**Comment by sharoni** [comment]
Issue resolved in AN SDK 6.3.0
