### ISSUE TITLE
Can not build and run project

### ISSUE THREAD

**Issue by finchatticus** [fbsamples/audience-network#130]
Getting gradle error:
A problem occurred configuring project ':AdUnitsSample'.
> Failed to notify project evaluation listener.
   > org.gradle.api.file.ProjectLayout.fileProperty(Lorg/gradle/api/provider/Provider;)Lorg/gradle/api/file/RegularFileProperty;

**Comment by ashaevy** [comment]
Likely Gradle configuration issue, doesn't happen for sample apps.
