### ISSUE TITLE
iOS Compilation Error with FBAudienceNetwork.framework

### ISSUE THREAD

**Issue by viktorcode** [fbsamples/audience-network#133]
1. Perform necessary steps to compile the sample app for iOS in Xcode.
2. For simplicity choose simulator target (but the bug is reproducible on any architecture)
3. It should compile successfully.
4. In Xcode project settings set Link-Time Optimisation (LLVM_LTO) to "Monolithic"

Compilation fails. Error (from compilation to simulator target):

```
ld: warning: linking module flags 'SDK Version': IDs have conflicting values ('[2 x i32] [i32 13, i32 6]' from /Users/viktorchernikov/Downloads/FBAudienceNetwork-6/Static/FBAudienceNetwork.framework/FBAudienceNetwork(FBANBannerAdAdapter.m.o) with '[2 x i32] [i32 14, i32 2]' from ld-temp.o)
ld: linking module flags 'Dwarf Version': IDs have conflicting behaviors in '/Users/viktorchernikov/Downloads/FBAudienceNetwork-6/Static/FBAudienceNetwork.framework/FBAudienceNetwork(FBANBannerAdAdapter.m.o)' and 'ld-temp.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

As a consequence, any iOS project that links against FBAudienceNetwork.framework can't be compiled with link-time optimisation enabled.

FBAudienceNetwork.framework v6.2.0
FBSDKCoreKit.framework v8.2.0
Xcode v12.2

**Comment by sharoni** [comment]
Hi @viktorcode, are you getting the same error with 6.3.0 version of AN SDK?

**Comment by viktorcode** [comment]
FBAudienceNetwork.framework v6.3.0
FBSDKCoreKit.framework v9.1.0
Xcode v12.4

The sample now builds and runs fine with Link-Time Optimisation on Monolithic.
