### ISSUE TITLE
Web for Mobile real status

### ISSUE THREAD

**Issue by QuentinCG** [fbsamples/audience-network#139]
Hello,

I'm not sure if your 'web for mobile' option is possible or not since all your examples are giving 'error 500': https://github.com/fbsamples/audience-network/tree/use_macro_app_id/samples/mobile_web/

If you don't use it, I would advise to be clear on the subject to not make people lose their time on this ad network (<=> get bad reputation for misleading people). Only article I can found are related on a 'beta' and your commit are 5 years old... Which seems to mean this web for mobile project is dead ?

Best regards

**Comment by onur-simsek** [comment]
As of Apr 11, 2020, Audience Network no longer fills any ad requests to web and in-stream placements.

source: https://www.facebook.com/business/help/645132129564436?id=211412110064838

**Comment by QuentinCG** [comment]
Thanks for your help !
