### ISSUE TITLE
Facebook Audience Network ads crash on Android devices

### ISSUE THREAD

**Issue by roma7481** [fbsamples/audience-network#140]
I see that Facebook Audience Network Native ads crash on Android devices for my users. The crash is happening on release version only. I am using the latest Facebook audience-network-sdk 6.2. I have apps with older sdk 5.7 and I don't see this issue. The crash is:

Fatal Exception: java.lang.NoSuchMethodError

No static method getSharedPreferences(Landroid/content/Context;)Landroid/content/SharedPreferences; in class Lcom/facebook/ads/internal/settings/AdSharedPreferences; or its super classes (declaration of 'com.facebook.ads.internal.settings.AdSharedPreferences' appears in /data/app/<app id>-1/base.apk) 

    com.facebook.ads.redexgen.X.4u.isTestMode (4u.java:12285)
    com.facebook.ads.internal.settings.AdInternalSettings.isTestMode (AdInternalSettings.java)
    com.facebook.ads.AdSettings.isTestMode (AdSettings.java)
    com.facebook.ads.redexgen.X.1m.A01 (1m.java:3656)
    com.facebook.ads.redexgen.X.SJ.A0D (SJ.java:52213)
    com.facebook.ads.redexgen.X.SJ.A0T (SJ.java:52288)
    com.facebook.ads.redexgen.X.SJ.A0U (SJ.java:52290)
    com.facebook.ads.redexgen.X.cD.A1U (cD.java:72218)
    com.facebook.ads.redexgen.X.Je.A00 (Je.java:40169)
    com.facebook.ads.redexgen.X.cD.loadAd (cD.java:72343)
    com.facebook.ads.NativeAdBase.loadAd (NativeAdBase.java)
    ads.NativeAdActivity.access$000 (NativeAdActivity.java)
	
Please help, couldn't find anything online.

**Comment by roma7481** [comment]
Have to put -keep class com.facebook.ads.** { *; }  in Proguard settings

**Comment by ashaevy** [comment]
Commented on https://github.com/facebook/facebook-android-sdk/issues/892
