### ISSUE TITLE
ClassCastException:com.facebook.ads.redexgen.X.Th.A0I 

### ISSUE THREAD

**Issue by NiaNingXue** [fbsamples/audience-network#141]
Hi, I update the audience network sdk to 6.2.1, crash happens on many users' devices, include android 6.0 - android 10. 
The previous version I use is 5.11.0 and has no this issue.
>java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.ViewGroup 
com.facebook.ads.redexgen.X.Th.A0I
com.facebook.ads.redexgen.X.5C.registerViewForInteraction
com.facebook.ads.NativeAd.registerViewForInteraction NativeAd.java:8
com.sample.app.ad.view.NativeAdView.bindNativeAd NativeAdView.java:20
android.view.View.measure View.java:20089
androidx.constraintlayout.widget.ConstraintLayout.onMeasure ConstraintLayout.java:72
android.view.View.measure View.java:20089
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6415
android.widget.FrameLayout.onMeasure FrameLayout.java:214
androidx.appcompat.widget.ContentFrameLayout.onMeasure ContentFrameLayout.java:21
android.view.View.measure View.java:20089
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6415
android.widget.LinearLayout.measureChildBeforeLayout LinearLayout.java:1705
android.widget.LinearLayout.measureVertical LinearLayout.java:797
android.widget.LinearLayout.onMeasure LinearLayout.java:657
android.view.View.measure View.java:20089
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6415
android.widget.FrameLayout.onMeasure FrameLayout.java:214
android.view.View.measure View.java:20089
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6415
android.widget.LinearLayout.measureChildBeforeLayout LinearLayout.java:1705
android.widget.LinearLayout.measureVertical LinearLayout.java:797
android.widget.LinearLayout.onMeasure LinearLayout.java:657
android.view.View.measure View.java:20089
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6415
android.widget.FrameLayout.onMeasure FrameLayout.java:214
com.android.internal.policy.DecorView.onMeasure DecorView.java:743
android.view.View.measure View.java:20089
android.view.ViewRootImpl.performMeasure ViewRootImpl.java:2640
android.view.ViewRootImpl.measureHierarchy ViewRootImpl.java:1577
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:1846
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1462
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:7013
android.view.Choreographer$CallbackRecord.run Choreographer.java:924
android.view.Choreographer.doCallbacks Choreographer.java:726
android.view.Choreographer.doFrame Choreographer.java:661
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:910
android.os.Handler.handleCallback Handler.java:836
android.os.Handler.dispatchMessage Handler.java:103
android.os.Looper.loop Looper.java:203
android.os.Handler.handleCallback Handler.java:836
android.os.Handler.dispatchMessage Handler.java:103
android.os.Looper.loop Looper.java:203
android.app.ActivityThread.main ActivityThread.java:6328
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:1076
com.android.internal.os.ZygoteInit.main ZygoteInit.java:937

**Comment by gwheet** [comment]
It's probably happens because you add MediaView directly into Activity root layout (ViewRootImpl). Create some child layout under ViewRootImpl, for example, FragmentLayout and add MediaView inside this layout. It should fix the issue.

**Comment by Nghicv** [comment]
Hi @RodXander. I am getting the same crash. Did you resolve the issue?

**Comment by momshardadevi** [comment]
hi,
I am also getting the same crash...

**Comment by sonusourav** [comment]
Facing the same issue, has anyone got any fix for this?

**Comment by tangeriner** [comment]
facebook-sdk is so terrible!
