### ISSUE TITLE
NullPointerException at DynamicLoaderImpl.java

### ISSUE THREAD

**Issue by appsapiconsole** [fbsamples/audience-network#143]
Facebook Audience Network Version 6.3.0
java.lang.NullPointerException: Attempt to read from null array at com.facebook.ads.internal.dynamicloading.DynamicLoaderImpl.createAudienceNetworkAdsApi(DynamicLoaderImpl.java:137) at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.doCallInitialize(DynamicLoaderFactory.java:161) at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.access$200(DynamicLoaderFactory.java:41) at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:121) at java.lang.Thread.run(Thread.java:818)
![image](https://user-images.githubusercontent.com/56867915/109783163-8151ed00-7c2b-11eb-8db0-1c2a9f2e44e2.png)
![image](https://user-images.githubusercontent.com/56867915/109783236-9595ea00-7c2b-11eb-8c0e-6e0fd4011d03.png)

**Comment by sergiambel** [comment]
Same error here

**Comment by NaveenDevrani** [comment]
same issue i am facing , please fix this issue very soon, lot's of user effected with this crash 
![Screenshot (4)](https://user-images.githubusercontent.com/37726754/112740265-2ba60180-8f99-11eb-8f1e-382c50f233ec.png)

**Comment by mmathieum** [comment]
I posted a bug report on Facebook as I'm not sure anyone at Facebook is seeing this:
https://developers.facebook.com/support/bugs/208906161009896/

**Comment by gwheet** [comment]
Thanks for posting the bug report on Facebook. The engineering team is looking into this issue, please use https://developers.facebook.com/support/bugs/208906161009896/ to track progress.
