### ISSUE TITLE
callback for facebook unfill

### ISSUE THREAD

**Issue by mnjit** [fbsamples/audience-network#18]
How can we get the callback when we get facebook audience network unfill error, is there any way?

**Comment by jch7557** [comment]
When you are using native for mobile app, you can subscribe to native ad notification and receive notification if ad loading failed. You can perform error handling from there.

For iOS, please refer to: 

- (void)nativeAd:(FBNativeAd *)nativeAd didFailWithError:(NSError *)error.

For Android, please refer to:

nativeAd.setAdListener(new AdListener() {
    @Override
    public void onError(Ad ad, AdError error) {
      // Ad error callback
    } 
...
}

**Comment by mnjit** [comment]
Hi @jch7557 thanks for your reply; but how we can handle it in case of web.
