### ISSUE TITLE
Unknown Error : Banner Ad

### ISSUE THREAD

**Issue by KChavda18** [fbsamples/audience-network#26]
Code Implementation : 
AdView adView = new AdView(this, "271995593270465_271996219937069", AdSize.BANNER_HEIGHT_50);//438544203147216_438545493147087
        AdSettings.addTestDevice(hashKey());
        adViewContainer.addView(adView);
        adView.setAdListener(new AdListener() {
            @Override
            public void onError(Ad ad, AdError adError) {
                Toast.makeText(MainActivity.this, "Error: " + adError.getErrorMessage(), Toast
                        .LENGTH_LONG).show();
            }

            @Override
            public void onAdLoaded(Ad ad) {
                Toast.makeText(MainActivity.this, "Ad loaded!", Toast.LENGTH_LONG).show();
            }

            @Override
            public void onAdClicked(Ad ad) {
                Toast.makeText(MainActivity.this, "Ad clicked!", Toast.LENGTH_LONG).show();
            }

            @Override
            public void onLoggingImpression(Ad ad) {
                Toast.makeText(MainActivity.this, "onLogging", Toast.LENGTH_LONG).show();
            }
        });
        adView.loadAd();

But, it's toast Unknown error

Help me to short out this issue....

**Comment by L33tcodex0r** [comment]
271995593270465_271996219937069 is not valid, it doesn't belong to a valid app.
