### ISSUE TITLE
Request new ad in recyclerview.

### ISSUE THREAD

**Issue by sumbganesh** [fbsamples/audience-network#29]
I have implemented ads in reycylerview in every 10th position. but when the ad loads, it display same ad in every position. How can i request new ad for new postion?

**Comment by phzhou** [comment]
Hi @sumbganesh please download the Facebook SDK from https://developers.facebook.com/docs/android 
It includes the Audience Network SDK and includes a NativeAdSample project that demonstrate your use case. Thanks!

**Comment by sumbganesh** [comment]
On line 152, replace ` mAd = mAds.nextNativeAd();` with `NativeAd mAd = mAds.nextNativeAd();`. I don't remember exactly if this was the solution, but give it a try.

**Comment by kimnamcham** [comment]
Thanks, i will try it
