### ISSUE TITLE
The parameter PLACEMENT_ID is required

### ISSUE THREAD

**Issue by ankitbatra11** [fbsamples/audience-network#31]
Hi,
Native ads aren't loading anymore with latest version of audience network 4.24.0. I am getting below error code and message:

`errorCode=1203 message=(#100) The parameter PLACEMENT_ID is required`

and this is how I create my native ad:

`nativeAd = new NativeAd(context, id /* placement ID */);`

**Comment by phzhou** [comment]
Hi @ankitbatra11 can you reproduce the bug in the Native Ad sample included in the 4.24 SDK? 
https://developers.facebook.com/docs/android

If not can you try to post more details of your code, how the ad is loaded and rendered, or try to attach a sample that can reproduce the problem you described? 

Thanks

**Comment by ankitbatra11** [comment]
I can reproduce the issue with 4.24.

**Comment by phzhou** [comment]
Hi @ankitbatra11 can you post more complete code so we can better understand what's happening?

**Comment by ankitbatra11** [comment]
It was an issue with canary Android studio and custom plugins. Using the latest stable release without Jack compiler solved the issue for me.
