### ISSUE TITLE
On some device (Lenovo Phab Plus 5.0.2, genymotion 5.0.0) rewarded video don't start and back button locked

### ISSUE THREAD

**Issue by BaxterZA** [fbsamples/audience-network#32]
In logcat:
07-03 11:06:19.461 13663-13663/com.my.test E/MediaPlayer: Should have subtitle controller already set
07-03 11:06:19.463 7291-7616/? D/NuPlayerDriver: start(0xf2e0c340)
07-03 11:06:19.463 7291-13837/? I/GenericSource: start
07-03 11:06:19.705 7291-13860/? E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
07-03 11:06:20.056 7291-13860/? E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -2147483648
07-03 11:06:20.079 7291-13864/? I/SoftAAC2: limiting to stereo output
07-03 11:06:20.101 7291-13864/? I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
07-03 11:06:20.138 7291-13856/? D/AudioSink: bufferCount (8) is too small and increased to 12
07-03 11:06:20.140 7291-13862/? E/SoftAVC: Decoder failed: -2
07-03 11:06:20.140 7291-13860/? E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
07-03 11:06:20.140 7291-13860/? E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
07-03 11:06:20.140 7291-13858/? E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
07-03 11:06:20.141 7291-13857/? E/NuPlayerDecoder: Failed to dequeue output buffer for OMX.google.h264.decoder (err=-38)
07-03 11:06:20.141 7291-13837/? E/NuPlayer: received error(0xffffffda) from video decoder, flushing(0), now shutting down
07-03 11:06:20.142 13663-13679/com.my.test E/MediaPlayer: error (1, -38)
07-03 11:06:20.142 7291-13857/? E/NuPlayerDecoder: failed to flush OMX.google.h264.decoder (err=-38)
07-03 11:06:20.142 13663-13663/com.my.test E/MediaPlayer: Error (1,-38)
07-03 11:06:20.142 7291-13837/? E/NuPlayer: received error(0xffffffda) from video decoder, flushing(2), now shutting down
07-03 11:06:20.142 13663-13663/com.my.test E/MediaPlayer: stop called in state 0
07-03 11:06:20.142 13663-13663/com.my.test E/MediaPlayer: error (-38, 0)
07-03 11:06:20.142 7291-7616/? D/NuPlayerDriver: reset(0xf2e0c340)
07-03 11:06:20.165 7291-13837/? D/NuPlayerDriver: notifyResetComplete(0xf2e0c340)
07-03 11:06:20.165 13663-13839/com.my.test E/MediaPlayer: error (1, -38)
07-03 11:06:20.166 7291-8090/? D/NuPlayerDriver: reset(0xf2e0c340)
07-03 11:06:22.911 7291-7614/? W/AudioFlinger: write blocked for 9805 msecs, 4 delayed writes, thread 0xf3701000

**Comment by phzhou** [comment]
We changed video rendering in later SDK versions.
Please update to the latest SDKs and feel free to open issue again if the same issue persists!
Thank you
