### ISSUE TITLE
Same ad is shown in RecyclerView.

### ISSUE THREAD

**Issue by sumbganesh** [fbsamples/audience-network#34]
I am using native ads in recyclerview. but FAN shows same ad in all positions. Is there any way I can put new ad in every postion of my recyclerview?

**Comment by phzhou** [comment]
Hi @sumbganesh if you download the SDK from the Facebook developer site https://origincache.facebook.com/developers/resources/?id=audience-network-sdk-4.25.0.zip
There is a native ad sample and one of the use case shows how to load ads in a RecyclerView.
Thanks!
