### ISSUE TITLE
Banner load first time always failed.

### ISSUE THREAD

**Issue by LazyBonesLZ** [fbsamples/audience-network#36]
I integrated Android FAN v4.24.0 SDK as docs says,but I found when first time to call "adView.loadAd()"(adView is a Adview Object), always received error 1001:" No fill,We are not able to serve ads to this person. Please refer to https://developers.facebook.com/docs/audience-network/faq#a12. If you are integrating Audience Network for the first time, you can use test ads https://developers.facebook.com/docs/audience-network/testing.", then I called "adView.loadAd()" again, ad was filled.

**Comment by phzhou** [comment]
Hi @LazyBonesLZ are you still able to reproduce the same issue in the SDK version 4.25.0?

**Comment by LazyBonesLZ** [comment]
@phzhou seems be fixed in the SDK v4.25.0

**Comment by phzhou** [comment]
Thanks for confirming @LazyBonesLZ
