### ISSUE TITLE
No static field notification_template_lines of type I in class Lcom/duanqu/qupainilui/R$layout;

### ISSUE THREAD

**Issue by yandesheng** [fbsamples/audience-network#37]
hello ,I want to confirm a question。
audience-network inside Appcompat-v7a？  version is 25.3.1. 
But our version is 24. How to solve this？ all the versions must correspond to it？

**Comment by phzhou** [comment]
Hi @yandesheng unfortunately yes we require that specific version to make use of the compile tools and utilities in 25.
