### ISSUE TITLE
After clicking on the interstitial's link, interstitial does't close.

### ISSUE THREAD

**Issue by garastard** [fbsamples/audience-network#38]
After clicking on the interstitial's link, interstitial doesn't close. This is the reason for interstitial remains visible when you return to the application after the browser is closed. How can I fix it?

**Comment by phzhou** [comment]
Hi @garastard this is typical ad experience for interstitials.
If you really want to change it in your app then maybe you can make use of the callback functions in the `InterstitialAdListener`
