### ISSUE TITLE
Updated Ads Gradle logged by ES File Explorer

### ISSUE THREAD

**Issue by girubhai** [fbsamples/audience-network#39]
Recently update gradle version to 4.25.0 as 

```
compile 'com.facebook.android:facebook-android-sdk:4.25.0'
compile 'com.facebook.android:audience-network-sdk:4.25.0'
```
Now ES File explorer's logger log the ads when Native Ads is being display which is irritating.
Note :  I am also using Google Native Express Ads but it is not logging. Please check.

To be more Clear :

ES File Explorer App having logger facility to show bubble at top of others app while media downloaded by Apps.Now I am using both Facebook Native ads and AdMob's NativeExpress Ads to show ads in my App.When Facebook NativeAds is being displayed, Logger appears top of the application and showing recent media downloaded. It is not happening with Admob Ads.

**Comment by phzhou** [comment]
Hi @girubhai I don't think this is issue for SDK integration or showing ads in your app?
There might be changes in this area but I think at the moment this is less priority than other issues

**Comment by girubhai** [comment]
@phzhou Thanks to reply.
It is serious issue because now a days most of users use ES File explorer app and  in my app if ES File Explorer will float with media download then user will not use my app.
So I have two option, either we include FB Advt or we should publish without.

Note : As I shared previously, On Google/Admob Native expressed Ad float is not appearing.

Once again thank you.

**Comment by phzhou** [comment]
Can you share some screenshots of what you described? Thanks!

**Comment by girubhai** [comment]
@phzhou  PFA
![fb ad issue](https://user-images.githubusercontent.com/3602562/29259246-d2d40ed4-80de-11e7-9e6d-664d006fdf76.jpg)

It was not as issue while using dependency version **4.10.1** but I have to update because of FB will not render ads on previous versions.

**Comment by girubhai** [comment]
@phzhou Did you check this?
