### ISSUE TITLE
NPE Attempt to invoke virtual method 'com.facebook.ads.internal.view.d.c.d com.facebook.ads.internal.view.j.getState()'

### ISSUE THREAD

**Issue by Baobomb** [fbsamples/audience-network#46]
Hi, it happened when inflate ViewGroup with MediaView.
Then get 
D/crash: android.view.InflateException: Binary XML file line #45: Error inflating class com.facebook.ads.MediaView
                                              at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                              .
                                              .
                                              .
                                              .
 Caused by: java.lang.reflect.InvocationTargetException
                                              at java.lang.reflect.Constructor.newInstance(Native Method) 
                                              .
                                              .
                                              .
                                              .
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.ads.internal.view.d.c.d com.facebook.ads.internal.view.j.getState()' on a null object reference at com.facebook.ads.internal.view.h.c(Unknown Source)
                                              .
                                              .
                                              .
                                              .
After review com.facebook.ads.internal.view.h 
I see 

    private a b() {
        return new a(this, 50, true, new com.facebook.ads.internal.j.a.a() {
            public void a() {
                if(h.this.g != null) {
                    if(!h.this.j && (h.this.i || h.this.shouldAutoplay())) {
                        h.this.play(VideoStartReason.AUTO_STARTED);
                    }

                    h.this.i = false;
                    h.this.j = false;
                }
            }
            public void b() {
                if(h.this.g != null) {
                    if(h.this.g.getState() == d.e) {
                        h.this.j = true;
                    } else if(h.this.g.getState() == d.d) {
                        h.this.i = true;
                    }

                    h.this.pause();
                }
            }
        });
     }

Maybe this g class doing something error?

**Comment by phzhou** [comment]
Hi @Baobomb can you let us know more details about your problem?
Which SDK version are you using?
What is your inflate process?
If you can provide code snippets that you were able to reproduce the problem that would be great help!
Thanks

**Comment by Baobomb** [comment]
SDK version : 4.25.0
It happend when try to inflate layout which include
MediaView.

**Comment by vmalykhin** [comment]
Happening on Android 4.x and 5.x devices using `audience-network-sdk:4.26.0`. Not reproduced on v.4.23.0, looks like the issue was introduced in 4.24.0.

**Comment by reiterp-avs** [comment]
@Baobomb Do you set the MediaView visibility attribute in your layout? In case you do, maybe you can avoid the NPE by not setting it and set it at runtime, after the view is inflated.

**Comment by phzhou** [comment]
Hi @Baobomb @vmalykhin unfortunately we weren't able to reproduce the problem. Would you mind provide a sample project so we can try to reproduce the problem? Thanks!

**Comment by reiterp-avs** [comment]
Hi, I have already reported the bug here https://developers.facebook.com/bugs/2003665309903654/ and the bug report includes sample.

**Comment by Sarun1001** [comment]
@phzhou @reiterp-avs Hi guys I'm also facing the same issue, app crashes while using SDK version above v.4.23.0. 

"Binary XML file line #59: Error inflating class com.facebook.ads.MediaViewCaused by: android.view.InflateException: Binary XML file line #59: Error inflating class com.facebook.ads.MediaViewCaused by: java.lang.reflect.InvocationTargetException"

**Comment by phzhou** [comment]
Hi @Baobomb @vmalykhin @reiterp-avs @Sarun1001 have you guys tried the latest SDK and see if it fixes your issue?
Also how are you guys using the SDK? Are you including it from the gradle build dependency, or include the SDK as aar file in the project libs folder?

**Comment by gregko** [comment]
Had the same problem on Android 5.1 (maybe others too, did not test). Per @reiterp-avs comment above, I removed:

   android:visibility="gone"

from the XML layout of the native ad, and I set the visibility as needed in Java code instead. This fixed the problem.
