### ISSUE TITLE
Update podspec

### ISSUE THREAD

**Issue by threat70** [fbsamples/audience-network#51]
Hi! 
What about update FBAudienceNetwork podspec to 4.27+ ? I suggest that you fixed iOS 11 issue here, and I want to update it through cocoapods.

Thanks

**Comment by phzhou** [comment]
Hi @threat70 !

The latest version for the Audience Network iOS SDK is 4.26.1 as listed here:
https://developers.intern.facebook.com/docs/audience-network/download#ios

We will update the podspec once 4.27+ is out =D

Thanks!

**Comment by threat70** [comment]
Hi @phzhou .
Sorry, I mixed up Audience Network SDK with common Facebook SDK.
