### ISSUE TITLE
FB6 RuntimeException - AsyncTask$3.done com.facebook.ads

### ISSUE THREAD

**Issue by HaloMego** [fbsamples/audience-network#52]
**## Hello,sir, SDK_Version =4.26.0,how to resolve the issue?**  
Exception java.lang.RuntimeException: An error occurred while executing doInBackground()
android.os.AsyncTask$3.done (AsyncTask.java:318)
java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
java.util.concurrent.FutureTask.setException (FutureTask.java:223)
java.util.concurrent.FutureTask.run (FutureTask.java:242)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

Caused by java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/[REDACTED_DOMAIN_NAME]/databases/ads.db
android.database.sqlite.SQLiteClosable.acquireReference (SQLiteClosable.java:55)
android.database.sqlite.SQLiteDatabase.endTransaction (SQLiteDatabase.java:522)
com.facebook.ads.internal.e.d$2.a (d.java)
com.facebook.ads.internal.e.d$2.b (d.java)
com.facebook.ads.internal.e.d$1.a (d.java)
com.facebook.ads.internal.e.d$1.doInBackground (d.java)
android.os.AsyncTask$2.call (AsyncTask.java:304)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

**Comment by phzhou** [comment]
Hi @HaloMego 

This is an issue that there is a small chance you can run into this error in 4.26.0
Please update to SDK version 4.26.1 which fixed this issue.

Thanks!
