### ISSUE TITLE
NativeAd not loaded

### ISSUE THREAD

**Issue by seshuvinay** [fbsamples/audience-network#57]
Gradle:
` compile 'com.facebook.android:audience-network-sdk:4.+'`

Code to display ad:

```
nativeAd = new NativeAd(getActivity(), "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
 AdSettings.addTestDevice("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
 nativeAd.setAdListener(new AdListener() {

                @Override
                public void onError(Ad ad, AdError error) {
                //not called
                }

                @Override
                public void onAdLoaded(Ad ad) {
                    //My code to inflate View


                }

                @Override
                public void onAdClicked(Ad ad) {
                   
                }

                @Override
                public void onLoggingImpression(Ad ad) {

                }
            });

            nativeAd.loadAd();
```
I am using above code to display Native Ads. Neither onAdLoaded nor onError is called. Didn't find anything in logs either.
Status of app is "Approved" and status of Ad space is "Enabled and received ad request recently"

**Comment by phzhou** [comment]
Hi @seshuvinay would you mind posting your activity class source code here to help us reproduce the issue? Thanks!

**Comment by seshuvinay** [comment]
It's in a Fragment. And I am using above code when Ad is to be displayed. Cant post complete Fragment here. But other than above code, there is nothing related to Native Ads.
My FAN dashboard shows this data:

![screenshot from 2018-01-19 13-55-58 copy](https://user-images.githubusercontent.com/2959220/35141545-3e4d716e-fd21-11e7-9a2c-97ddbf599718.jpg)

**Comment by phzhou** [comment]
Hi @seshuvinay I'm afraid it's hard to help you debug without any source code to reproduce the issue.
It seems that you are receiving the ad correctly, but there is something wrong with showing the ad in the layout.

Could you try to follow exactly the Native ad document here
https://developers.facebook.com/docs/audience-network/android-native
And verify if the problem still exist?

**Comment by phzhou** [comment]
Please update with the latest SDK and feel free to re-open if problem still exists
