### ISSUE TITLE
call SDK get AD Fail ，crash.

### ISSUE THREAD

**Issue by MirindaLiu** [fbsamples/audience-network#6]
0  messagebirds                   0x10034d67c -[CTBanner nativeAd:didFailWithError:](CTBanner.m:1083)
1  messagebirds                   0x100309a64 -[FBNativeAd displayAdController:didFailWithError:](FBNativeAd.m:330)
2  messagebirds                   0x1002cb67c -[FBDisplayAdController notifyAdError:](FBDisplayAdController.m:322)
3  messagebirds                   0x1002cd438 -[FBDisplayAdController onAdRequestError:](FBDisplayAdController.m:693)
4  messagebirds                   0x100321cc0 -[FBAdProvider dispatchError:](FBAdProvider.m:136)
5  messagebirds                   0x100321904 **42-[FBAdProvider loadAdWithEnvironmentData:]_block_invoke.21 (FBAdProvider.m:72)
6  libdispatch.dylib              0x18087d200 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x18087d1c0 _dispatch_client_callout + 16
8  libdispatch.dylib              0x180881d6c _dispatch_main_queue_callback_4CF + 1000
9  CoreFoundation                 0x1819a1f2c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE** + 12
10 CoreFoundation                 0x18199fb18 __CFRunLoopRun + 1660
11 CoreFoundation                 0x1818ce048 CFRunLoopRunSpecific + 444
12 GraphicsServices               0x183351198 GSEventRunModal + 180
13 UIKit                          0x1878a7818 -[UIApplication _run] + 684
14 UIKit                          0x1878a2550 UIApplicationMain + 208
15 messagebirds                   0x10007d30c main (main.m:18)
16 libdispatch.dylib              0x1808b05b8 (Missing)

**Comment by MirindaLiu** [comment]
DAU：20000+      crash：5000+

**Comment by jch7557** [comment]
Please try the latest SDK and provide the feedback if the same issue is observed.
