### ISSUE TITLE
Possible race condition in RewardedVideoAd initializing the ExoPlayer

### ISSUE THREAD

**Issue by jitesh-pz** [fbsamples/audience-network#62]
**ISSUE DETAILS:**

We are using a custom URLStreamHandlerFactory in our project, setting it via URL#setURLStreamHandlerFactory. The RewardedVideoAd video playing stucks for us. The player doesn't send a GET request to the video URL. But the everything works fine, if we don't use a custom handler.

For isolating the bug, we created a dummy handler which just uses the platform default protocol handlers and passes on to them. The same issue persists with the dummy handler too.

If we insert a time delay of 1-2 seconds in URLStreamHandler#openConnection method of the handlers returned by our factory, it makes the video play. This hints towards a race condition or similar concurrency bug in the way RewardedVideoAd class interacts with ExoPlayer (possibly when it tries to initialize the player).

**STEPS TO REPRODUCE:**

1. Clone the repository: https://github.com/jitesh-pz/facebook-ad-video-issue
2. Open the project in android studio, build and deploy to a device
3. From the main menu of the app, go to "Rewarded Videos" section, click on "Load Rewarded Video", once loaded, click "Show"
4. The video player will stuck in the loading stage. (this is the bug)
5. Now, from MainActivity.java, comment out line 53 (URL.setURLStreamHandlerFactory call). Build the app again, video playing will start working.
6. To confirm the concurrency bug, uncomment the same line in previous step, and uncomment lines 86 and 95 (sleep calls) to introduce a delay, build the app again, video will start playing.

**ADDITIONAL INFO:**

SDK Version: 4.28.0 (compile 'com.facebook.android:audience-network-sdk:4.+')
Occurs independent of any particular device model, android version.. etc

![screenshot_2018-03-13-15-21-50-490_com facebook audiencenetwork adssample](https://user-images.githubusercontent.com/37329289/37334806-ecd27b1e-26d2-11e8-9289-545ec90d2dc6.png)
![screenshot_2018-03-13-15-21-42-469_com facebook audiencenetwork adssample](https://user-images.githubusercontent.com/37329289/37334807-ed1ce550-26d2-11e8-9317-4f1d81747a22.png)
![screenshot_2018-03-13-15-21-32-148_com facebook audiencenetwork adssample](https://user-images.githubusercontent.com/37329289/37334808-ed61a992-26d2-11e8-8376-aaee4a44e0be.png)
![screenshot_2018-03-13-15-21-18-331_com facebook audiencenetwork adssample](https://user-images.githubusercontent.com/37329289/37334809-ed915610-26d2-11e8-9214-12ec3ea04e16.png)

**Comment by jitesh-pz** [comment]
reported here also:
https://developers.facebook.com/bugs/637879549877426/

**Comment by phzhou** [comment]
Closing as fixed in the bug tracking tool above
