### ISSUE TITLE
How to Native Ads in very large items list.

### ISSUE THREAD

**Issue by Asad4429** [fbsamples/audience-network#63]
Hey i want to show native ads in my feed list which is almost unlimited.
I used facebook's NativeAdsManager with RecyclerView as Sample code does but problem is that it limits 10 and i want to load more Ads. i am showing ad after every 5 items. Is there any efficient way to load 2 or 3 ads with NaticeAdsManager first and request more ads as list gets scroll?

**Comment by charlizesmith** [comment]
Hi Asad4429,
Did you found any solution? I am also facing the same issue.

**Comment by creativityingenuity** [comment]
me too ,and my recyclerview After adding an ad, it’s very Caton.
