### ISSUE TITLE
Received status code 403 from server: Forbidden how to solve this please give me a solution .. 

### ISSUE THREAD

**Issue by MathanSara** [fbsamples/audience-network#65]
When am using new latest SDK `implementation 'com.facebook.android:audience-network-sdk:4.32.0'` also gradle version is `com.android.tools.build:gradle:3.1.1` , now rebuild the project but it shows error on `Received status code 403 from server: Forbidden`

    Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.facebook.android:audience-network-sdk:4.32.0.

    Could not resolve com.facebook.android:audience-network-sdk:4.32.0.
    Required by:
    project :app
    > Could not resolve com.facebook.android:audience-network-sdk:4.32.0.
    > Could not get resource 'https://s3.amazonaws.com/moat-sdk-builds/com/facebook/android/audience-network-sdk/4.32.0/audience-network-sdk-4.32.0.pom'.
          > Could not GET 'https://s3.amazonaws.com/moat-sdk-builds/com/facebook/android/audience-network-sdk/4.32.0/audience-network-sdk-4.32.0.pom'. Received status code 403 from server: Forbidden

Please give me a right solution. Still 3 days i search lot of links but no use.

**Comment by chrisma0101** [comment]
Hi, thanks for reporting this. Could you please try implementation 'com.facebook.android:audience-network-sdk:4.28.1' because 4.28.1 is our latest SDK version? Please check out developer docs for more SDK versions information. (https://developers.facebook.com/docs/audience-network/download)

Thanks,
Chris

**Comment by MathanSara** [comment]
thank you so much chrisma0101
