### ISSUE TITLE
Strong retain cycle with Native Ad

### ISSUE THREAD

**Issue by kried** [fbsamples/audience-network#66]
I've found a memory leak in [your native sample](https://github.com/fbsamples/audience-network/tree/master/samples/ios/native). 

If I set `nativeAd.mediaCachePolicy = FBNativeAdsCachePolicyNone;`
and then I comment image loading images using method `loadImageAsyncWithBlock:` and don't download images, I see a retain cycle in memory graph.
<img width="343" alt="leak" src="https://user-images.githubusercontent.com/3630656/39359289-211a4f1a-4a22-11e8-9a94-ba944163ef84.png">

**Comment by andrliu** [comment]
Hi @kried, thanks for your feedback, we will look into that.

**Comment by andrliu** [comment]
Hi @kried, please refer to our latest sdk and sample code.
