### ISSUE TITLE
com.facebook.ads.internal.view.n.setVideoMPD

### ISSUE THREAD

**Issue by phantuanphong** [fbsamples/audience-network#67]
I received a lot of crash report, it show cause: com.facebook.ads.internal.view.n.setVideoMPD

**Comment by aliguvenc** [comment]
same as me, i got tons of crash report. Below is my logcat.
[com.teknasyon.relaxingsounds_issue_212_crash_5B1069B003B300013C5F903367B963F4_DNE_0_v2.txt](https://github.com/fbsamples/audience-network/files/2061601/com.teknasyon.relaxingsounds_issue_212_crash_5B1069B003B300013C5F903367B963F4_DNE_0_v2.txt)

**Comment by aliguvenc** [comment]
yeah, same as me. I got tones also tones of crash report. Below is my crash report.
[https://github.com/fbsamples/audience-network/issues/67](logcat)

**Comment by aliguvenc** [comment]
yeah, same as me. I got tones of crash report about com.facebook.ads.internal.view.n.setVideoMPD.
Below is my logcat.
[logcat.txt](https://github.com/fbsamples/audience-network/files/2061621/logcat.txt)

**Comment by chrisma0101** [comment]
Hi,
    I saw your log file, and seems you were populating the native ad into recycler view cell. May I have the code snippet of "populateFacebookNativeAdView" such that I can reproduce the crash?
Thanks,
Chris
