### ISSUE TITLE
Always return error 1001 no fill

### ISSUE THREAD

**Issue by cosfun** [fbsamples/audience-network#70]
In version 4.28.1，use "AdSettings.addTestDevice" i can see TestAd.
but now always return error 1001 no fill

response like:
`{"type":"error","code":1001,"message":"No fill","placements":[{"definition":{"placement_id":"264358014310343_265421714203973","type":"native","refresh":"0","refresh_threshold":"-1","min_viewability_percentage":"1","viewability_check_ticker":"0","viewability_check_interval":"100","viewability_check_initial_delay":"0","video_time_polling_interval":"200","cacheable":false,"client_max_retry_count":"1","invalidation_duration_in_seconds":"3600","conv_tracking_data":[{"url":"\/\/.facebook.com","key":"fr","value":"0o2U1C7KoCwwrwRUU.AWUpB5UZViaWqFDlNjhXTJG1Q00.BbNKQC..AAA.0.0.BbNKQC.AWUsNwjp","expiration":"1537952514"},{"url":"\/\/.atdmt.com","key":"ATX","value":"cdc2006e03eab69fcfbab9cf18f6f6f2518a2805","expiration":"1537952514"}]},"feature_config":{"adnw_android_video_caching_enabled":"true","adnw_enable_exoplayer":"false","adnw_enable_iab":"true","adnw_debug_logging":"true","adnw_block_lockscreen":"false","adnw_enable_debug_overlay":"false","adnw_ios_use_store_url":"true","adnw_client_request_id_enabled":"true","adnw_native_cookie_injection":"false","adnw_top_activity_viewability":"false","adnw_enhanced_viewability_area_check":"false","adnw_ios_watch_and_install":"false","adnw_android_disable_playable_precache":"false","adnw_android_disable_blur":"false","adnw_android_memory_opt":"false","adnw_viewability_check_area_based":"false","adnw_mapp_markup_impression_after_image_load":"false","adnw_ios_blur_images_enabled":"false","adnw_enable_inline_x_out_on_sdk":"false","adnw_android_wo_bot_detection_enabled":"false","unified_logging_immediate_delay_ms":"2000","adnw_purge_on_413_response":"false","ad_viewability_tap_margin":"0","minimum_elapsed_time_after_impression":"-1","visible_area_check_enabled":"false","visible_area_percentage":"50","disable_in_app_app_store":"true","unified_logging_event_limit":"30","video_and_endcard_autorotate":"autorotate_enabled","stack_trace_sample_rate":"100","show_metadata_rewarded_video":"true","show_play_pause_rewarded_video":"true","additional_debug_logging_sampling_percentage":"100","wo_bot_detection_config":"s:30,a:0","adnw_logging_endpoint_prefix":"www"},"ads":[]}]}`

**Comment by phzhou** [comment]
Hi @cosfun, when you are not sending ad request in the test mode, please refer to the testing document here for how to test with production ads
