### ISSUE TITLE
fbadnw.js 404

### ISSUE THREAD

**Issue by dcy** [fbsamples/audience-network#73]
Hi!
![_ _20180816142856](https://user-images.githubusercontent.com/1137238/44192113-ce9b0b80-a160-11e8-9ddf-ac2aeb03ec1f.png)
https://connect.facebook.net/en_US/fbadnw.js 404

**Comment by phzhou** [comment]
Hi @dcy sorry this is a deprecated sample, will be removed soon.
For mobile web integrations please refer to the latest documentation from here:
https://developers.intern.facebook.com/docs/audience-network/web

**Comment by dcy** [comment]
![_ _20180823144602](https://user-images.githubusercontent.com/1137238/44509145-580f8800-a6e3-11e8-9458-6585a84931e1.png)
