### ISSUE TITLE
After migrating from 4.23.0 to 5.0.0 Test Device Always get error 1001 no fill 

### ISSUE THREAD

**Issue by Gaurav-kumarr** [fbsamples/audience-network#77]
I use designated test devices for testing Audience Network integrations and they are configured for real advertiser content in testing enabled mode as mentioned in Using Test Devices [https://developers.facebook.com/docs/audience-network/testing](url) and have all the necessary requirement and work on 4.23.0 SDK.

It is displaying real advertiser content with 4.23.0 SDK and worked well for me for a long time but when I try to switch to 5.0.0 SDK or 5.0.1 or 5.1.0 Beta with all necessary changes for migration I always get error 1001 no fill in all of my test devices.

When I add hash id for test ads then these devices receive test ads.

From last week I have no success in getting real Audience Network advertisements in our test devices with 5+ Audience Network Sdk

**Comment by andrliu** [comment]
Hi @Gaurav-kumarr, would you mind to contact our support team on Monetization Manager and provide your placement id. They should be able to look into your account and tell you more about the error you got.
