### ISSUE TITLE
5.1.0-beta android implementation

### ISSUE THREAD

**Issue by brunopiovan** [fbsamples/audience-network#78]
Hello,
I'm trying to implement 5.1.0-beta on my android app, however it's not clear on the beta SDK page how to do it.

```
<com.facebook.ads.NativeAdLayout
    android:id="@+id/native_ad_container"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical" />
```

```
// Add the AdOptionsView
LinearLayout adChoicesContainer = findViewById(R.id.ad_choices_container);
AdOptionsView adOptionsView = new AdOptionsView(NativeAdActivity.this, nativeAd, nativeAdLayout);
adChoicesContainer.removeAllViews();
adChoicesContainer.addView(adOptionsView, 0);
```

That's what the page currently has, but I'm not sure what `ad_choices_container`, `nativeAd` and `nativeAdLayout` are.

Does anybody have a better example on how to implement it?

**Comment by phzhou** [comment]
Hi! Sorry for the inconvenience, AdOptionsView has become part of our recommended native ad design. Please refer to the latest native ad sample about the usage of the views and classes. Thank you!
