### ISSUE TITLE
Connection was leaked warning

### ISSUE THREAD

**Issue by ziad-halabi9** [fbsamples/audience-network#79]
My logs are showing a warning saying:
`W/OkHttpClient: A connection to http://127.0.0.1:32873/ was leaked. Did you forget to close a response body?`

It's showing when loading native ads using `NativeAdsManager`. The Ads are usually being loaded.

I am using the 5.0.1 version. My compile and target sdk version is 28. The support libraries are all 28.0.0. And I do declare `android:networkSecurityConfig="@xml/network_security_config"` in my manifest. 

Am I missing something or should this warning be ignored? Thank you.

**Comment by phzhou** [comment]
Hi @ziad-halabi9 are you still having the same issue with the latest SDK versions? Thank you!

**Comment by phzhou** [comment]
If this is still an issue please feel free to use https://developers.facebook.com/support/bugs/ to report a bug and get in touch with product engineers. Thank you!
