### ISSUE TITLE
NativeAdListener not callback

### ISSUE THREAD

**Issue by JunlongLiang** [fbsamples/audience-network#80]
After the native.loadAd() is called in the SDK of 4.99.0 or above, the NativeAdListener has no callbacks. 
I can't know if its request was a success or a failure.

But when I use the test adUnitId, the NativeAdListener will callback.
(For example: VID_HD_16_9_46S_APP_INSTALL#xxxxxxxx_xxxxxxxxxx)

So this error will only appear in the AdUnitId of release.

**Comment by BCsl** [comment]
Same probleam when upgrade to 5.1.0.

**Comment by ldxlxl** [comment]
Same probleam when upgrade to 5.1.0.

**Comment by phzhou** [comment]
Hi @JunlongLiang @BCsl @ldxlxl are you still experiencing the same issue on the latest SDK version?
If so please provide your code sample to help us reproduce the issue, thank you!
