### ISSUE TITLE
 How to make MediaView video not enter full screen

### ISSUE THREAD

**Issue by TomyKissy** [fbsamples/audience-network#83]
How to make the video of NativeAd's MediaView not enter full-screen playback？
When you click on the video, it will enter full screen playback.Why？
I need to jump directly instead of playing the video in full screen.

Version:V5.1.0

**Comment by phzhou** [comment]
Hi @TomyKissy sorry but this is by design of Audience Network native ad experience. Clicking on the video will enter full screen video playback with sound, and there would be a call to action button at the corner of the screen to jump to the destination.
