### ISSUE TITLE
Complete samples with facebook-test-ads

### ISSUE THREAD

**Issue by ghost** [fbsamples/audience-network#87]
Hello Sirs,

May I ask if you could make your code ***complete*** with facebook test ads? I mean:

- The code uses ***your*** test placement IDs. For God sake, can you produce your own test placement IDs, instead of _"YOUR PLACEMENT ID"_?

- Once built, the app _shows_ test ads.

Benefits are:

- Developers will not have to change _"YOUR PLACEMENT ID"_ in your code. For God sake, do you know that if developers do that, it _messes_ up the local cloned git project?

- Developers only need to build the app first, to see if your code works or not. For God sake, how do we know if your code works or not? We _need_ a running sample app. Then next step we will write our own code. _Don't-you-ever_ tell us your code will always work.

Please, you are ***facebook*** developers. You are ***USA*** developers. Do you need these suggestions?

**Comment by phzhou** [comment]
Hi, please refer to the latest testing document
https://developers.facebook.com/docs/audience-network/testing

We provide multiple ways of testing including using test devices feature so you can test with test ads with your real placement ids. 

Thanks
