### ISSUE TITLE
FBMonotonicTimeGetCurrentMilliseconds crash

### ISSUE THREAD

**Issue by artwl** [fbsamples/audience-network#92]
Our game was developed using the cocos engine, adding the audience network SDK, using the IOS native code encoding, called in cocos.

Now I have a crash problem. We guess that it is likely to be related to the cocos engine (because the game developed with unity did not encounter this problem), but after a long time of debugging, we still have not solved the problem. The detailed crash information is as follows, and I want to get official help. Thank you!

```
#0 Thread SIGSEGV SEGV_ACCERR
```
index|msg
-- | --
0 JavaScriptCore | _llint_slow_path_get_by_id + 4576
1 JavaScriptCore | _llint_slow_path_get_by_id + 88
2 JavaScriptCore | _llint_entry + 11668
3 JavaScriptCore | _llint_entry + 29116
4 JavaScriptCore | _llint_entry + 29116
5 JavaScriptCore | _llint_entry + 29232
6 JavaScriptCore | _llint_entry + 29116
7 JavaScriptCore | _llint_entry + 29232
8 JavaScriptCore | _llint_entry + 29116
9 JavaScriptCore | _vmEntryToJavaScript + 272
10 JavaScriptCore | JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 184
11 JavaScriptCore | JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 464
12 JavaScriptCore | JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 168
13 JavaScriptCore | JSObjectCallAsFunction + 392
14 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 13617696
15 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 13666396
16 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 13665748
17 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 12554340
18 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 12553840
19 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 12536532
20 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 12536344
21 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 12537692
22 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 12536828
23 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 12696020
24 truckb-mobile | FBMonotonicTimeGetCurrentMilliseconds + 12573332
25 UIKit | __UIGestureEnvironmentSortAndSendDelayedTouches + 4340
26 UIKit | __UIGestureEnvironmentUpdate + 1236
27 UIKit | -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 404
28 UIKit | -[UIGestureEnvironment _updateGesturesForEvent:window:] + 276
29 UIKit | -[UIWindow sendEvent:] + 3132
30 UIKit | -[UIApplication sendEvent:] + 340
31 UIKit | ___dispatchPreprocessedEventFromEventQueue + 2340
32 UIKit | ___handleEventQueueInternal + 4744
33 UIKit | ___handleEventQueueInternal + 5608
34 UIKit | ___handleEventQueueInternal + 5608
35 UIKit | ___handleHIDEventFetcherDrain + 152
36 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
37 CoreFoundation | ___CFRunLoopDoSources0 + 456
38 CoreFoundation | ___CFRunLoopRun + 1204
39 CoreFoundation | CFRunLoopRunSpecific + 552
40 GraphicsServices | GSEventRunModal + 100
41 UIKit | UIApplicationMain + 236
42 truckb-mobile | __cxa_throw + 133928
43 libdyld.dylib | _start + 4

**Comment by cunzhegao** [comment]
We have encountered the same crash, though our game is built with Unity.

**Comment by andrewliu-code** [comment]
Hi @artwl and @cunzhegao, can you share more information, like SDK version and steps to reproduce the issue. If you can provide a sample code for us to debug that would be nice

**Comment by artwl** [comment]
Hi @andrewliu-code ,the Audience Network SDK Version is 5.1.1.  

The crash log is very frequent. We tested with real mobile phones and found that this crash log will appear frequently, but the app only occasionally crashes.

Below is a small portion of the crash log record:

| Index  | Version | Exception  Time | Device | OS Version |
|-|-|-|-|-|
| # 2532835 | 2.0.8(2.0.8) | 2019-05-11 10:37:20 020 | iPad Mini 4 | 11.4.1 (15G77)|
| # 2623368 | 2.0.8(2.0.8) | 2019-05-11 10:33:19 314 | iPad Air 2  | 12.2 (16E227)|
| # 2625753 | 2.0.7(2.0.7) | 2019-05-11 10:33:12 059 | iPad Air 2  | 12.2 (16E227)|
| # 2567589 | 2.0.8(2.0.8) | 2019-05-11 10:29:33 166 | iPhone 6    | 10.2.1 (14D27)|
| # 2561236 | 2.0.8(2.0.8) | 2019-05-11 10:29:10 597 | iPad mini 2 | 10.3.1 (14E304)|
| # 2621015 | 2.0.8(2.0.8) | 2019-05-11 10:26:47 590 | iPad mini 2 | 12.1 (16B92)|
| # 2560174 | 2.0.8(2.0.8) | 2019-05-11 10:26:11 968 | iPad Air 2  | 12.1.4 (16D57)|
| # 2618238 | 2.0.8(2.0.8) | 2019-05-11 10:25:44 091 | iPad mini 2 | 12.2 (16E227)|
| # 2564199 | 2.0.8(2.0.8) | 2019-05-11 10:25:41 126 | iPad Air 2  | 12.2 (16E227)|
| # 2567588 | 2.0.8(2.0.8) | 2019-05-11 10:21:54 142 | iPad mini 2 | 10.1 (14B72)|
| # 2531808 | 2.0.8(2.0.8) | 2019-05-11 10:21:07 376 | iPad 3  9.3.| 5 (13G36)|
| # 2620235 | 2.0.8(2.0.8) | 2019-05-11 10:20:32 488 | iPad Air    | 12.1.4 (16D57)|
| # 2623570 | 2.0.8(2.0.8) | 2019-05-11 10:18:03 414 | iPad mini 2 | 10.3.1 (14E304)|
| # 2623168 | 2.0.7(2.0.7) | 2019-05-11 10:16:12 185 | iPad Air 2  | 12.1.4 (16D57)|
| # 2562225 | 2.0.7(2.0.7) | 2019-05-11 10:10:09 020 | iPad Air    | 12.2 (16E227)|
| # 2626533 | 2.0.8(2.0.8) | 2019-05-11 10:09:58 819 | iPad mini 2 | 11.3.1 (15E302)|
| # 2576875 | 2.0.8(2.0.8) | 2019-05-11 10:08:42 322 | iPad Air 2  | 11.2.6 (15D100)|
| # 2622967 | 2.0.8(2.0.8) | 2019-05-11 10:07:14 491 | iPad Air 2  | 12.2 (16E227)|
| # 2562224 | 2.0.8(2.0.8) | 2019-05-11 10:06:49 233 | iPad Air 2  | 12.2 (16E227)|
| # 2625350 | 2.0.8(2.0.8) | 2019-05-11 10:06:18 113 | iPad Air    | 11.2.5 (15D60)|
| # 2619034 | 2.0.8(2.0.8) | 2019-05-11 10:05:55 550 | iPad Air    | 12.2 (16E227)|
| # 2625154 | 2.0.8(2.0.8) | 2019-05-11 10:05:19 540 | iPad mini   | 9.3.5 (13G36)|
| # 2551633 | 2.0.8(2.0.8) | 2019-05-11 10:04:03 732 | iPad Air    | 12.1.4 (16D57)|
| # 2625536 | 2.0.8(2.0.8) | 2019-05-11 10:02:26 793 | iPad Air    | 12.2 (16E227)|
