### ISSUE TITLE
AudienceNetworkAds.initialize() error in Logcat (Android Studio)

### ISSUE THREAD

**Issue by Izzyjm** [fbsamples/audience-network#93]
Hello when running my app in Android Studio I get this log in the logcat "You don't call AudienceNetworkAds.initialize(). Some functionality may not work properly" but no where in the FAN network documentation did it ever mention to make this call or didn't even show in the example code so how will developers know to include this ? and what functionality wouldn't' work properly because Im still receiving ads ? also I don't call an initialize method in my iOS app for FAN ads and I don't receive this warning so i'm kind of of confused why the documentation here makes no mention of this "intialize()" method ? ( https://developers.facebook.com/docs/audience-network/android-banners )

**Comment by phzhou** [comment]
Hi! Sorry for not being very clear in the banner sample specifically about initializing the SDK. 
Please refer to the sample code [here](https://github.com/fbsamples/audience-network/blob/master/samples/android/AdUnitsSample/AdUnitsSample/src/main/java/com/facebook/samples/AdUnitsSample/AudienceNetworkInitializeHelper.java) about the SDK initialization. We would update the documentation shortly as well.
Thank you!

**Comment by Izzyjm** [comment]
@phzhou is there an equivalent method for iOS ?

**Comment by phzhou** [comment]
Hi @Izzyjm no there is no equivalent for iOS, initialization of SDK is only for Android

**Comment by Izzyjm** [comment]
@phzhou I implemented AudienceNetworkAds.initialize(); but I am getting an error , what am I suppose to put inside the parenthesis ?

**Comment by Izzyjm** [comment]
?

**Comment by phzhou** [comment]
Hi @Izzyjm please refer to the documentation for sdk initialisation here:
https://developers.facebook.com/docs/audience-network/android-sdk-initialize
Thanks!

**Comment by Izzyjm** [comment]
@phzhou do we have to implement the helper class, or can we just call AudienceNetworkAds.initialize(); ?

**Comment by AntRemo** [comment]
Hi @phzhou 

I have the same question as @Izzyjm 

Thanks

**Comment by AG-Developers** [comment]
> Hello when running my app in Android Studio I get this log in the logcat "You don't call AudienceNetworkAds.initialize(). Some functionality may not work properly" but no where in the FAN network documentation did it ever mention to make this call or didn't even show in the example code so how will developers know to include this ? and what functionality wouldn't' work properly because Im still receiving ads ? also I don't call an initialize method in my iOS app for FAN ads and I don't receive this warning so i'm kind of of confused why the documentation here makes no mention of this "intialize()" method ? ( https://developers.facebook.com/docs/audience-network/android-banners )

I think you forget to use maven() and both dependencies of facebook (visit- https://developers.facebook.com/docs/audience-network/guides/adding-sdk/android )

without adding both dependencies you can not add AudienceNetworkAds.initialize();
-now no need to implement helper class, this is deprecated now.

Enjoy, Happy Coding :)
